name: PN.py
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07
  - certifi=2018.4.16
  - cycler=0.10.0
  - freetype=2.8
  - icc_rt=2017.*
  - icu=58.2
  - intel-openmp=2018.0.0
  - jpeg=9b
  - kiwisolver=1.0.1
  - libpng=1.6.34
  - matplotlib=2.2.2
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - numpy=1.14.2
  - openssl=1.0.2o
  - pip=10.0.1
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - python=3.6.5
  - python-dateutil=2.7.2
  - pytz=2018.4
  - qt=5.9.5
  - setuptools=39.1.0
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.23.1
  - tornado=5.0.2
  - vc=14
  - vs2015_runtime=14.0.25123
  - wheel=0.31.0
  - wincertstore=0.2
  - zlib=1.2.11
